In [16]:
import numpy as np
import pandas
np.random.seed(10)
scores =  np.random.randint(50,101, size=(50,5))
df = pandas.DataFrame(scores,columns=["國","英","數","自","社"],index=[f"學生{i}" for i in range(1,51)])
# df是DataFrame的實體 (內含屬性跟方法)
# type(df)

In [17]:
df.columns.name = "科目"
df.index.name = "姓名"

In [21]:
#  新增總分欄位
df['總分'] = df[['國', '英', '數', '自', '社']].sum(axis=1)
df["平均"] = df["總分"]/5
df

科目      國    英   數    自   社   總分    平均
姓名
學生1    59   86  65   50  99  359  71.8
學生2    78   75  79   98  79  409  81.8
學生3    99   58  59   50  92  358  71.6
學生4    90   86  66   86  97  425  85.0
學生5    61   74  93   83  58  369  73.8
學生6    86   64  99   63  55  367  73.4
學生7    63   75  63   78  72  351  70.2
學生8    80   80  75   62  51  348  69.6
學生9    81   86  77   68  79  391  78.2
學生10   63   72  73   80  61  349  69.8
學生11   78   60  74   59  65  336  67.2
學生12   68   66  57   74  61  326  65.2
學生13   67   96  57   61  78  359  71.8
學生14   83   70  82   74  94  403  80.6
學生15   55   54  57   74  74  314  62.8
學生16  100   94  84   90  65  433  86.6
學生17   63   74  65   56  71  329  65.8
學生18   92   72  61   98  62  385  77.0
學生19   78   82  99   65  94  418  83.6
學生20   90   92  95   93  83  453  90.6
學生21  100   95  90   75  59  419  83.8
學生22   87   50  68   73  53  331  66.2
學生23   79   66  70   68  98  381  76.2
學生24   64   65  67  100  75  371  74.2
學生25   96   98  92   67  82  435  87.0
學生26   67   91  66   91  76  391  78.2
學生27   62  100  80   67  67  376  75.2
學生28   66   50  81   87  59  343  68.6
學生29   50   88  72   82  52  344  68.8
學生30   53   81  85   77  68  364  72.8
學生31   63   93  98   79  95  428  85.6
學生32   61   99  72   87  61  380  76.0
學生33   71   83  81   93  74  402  80.4
學生34   82   87  59   90  87  405  81.0
學生35   93   93  76   57  58  377  75.4
學生36   71   58  78   95  80  382  76.4
學生37   75   75  64   67  71  352  70.4
學生38   63   91  83   54  73  364  72.8
學生39   80   78  89   77  89  413  82.6
學生40   59   57  72   82  53  323  64.6
學生41   59   62  54   80  56  311  62.2
學生42   96   60  80   59  52  347  69.4
學生43   51   99  88   92  63  393  78.6
學生44   61   55  79   97  70  362  72.4
學生45   98   92  84   90  96  460  92.0
學生46   82   80  72   55  95  384  76.8
學生47   68  100  98   94  51  411  82.2
學生48   93   63  68   77  69  370  74.0
學生49   87   57  74   89  65  372  74.4
學生50   56   94  59  100  50  359  71.8